project:
  type: book

book:
  title: "reprex-essentials"
  author: "Nicholas Tierney"
  date: "4/9/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - usethis-settings.qmd
    - examples.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



